services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: heart4edu-backend
    env_file: .env
    expose:
      - "8000"
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ORT_PROVIDERS=${ORT_PROVIDERS}

  # Build frontend (dist) lalu salin ke volume bersama nginx
  frontend-build:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_ENABLE_MOCK_DATA: ${VITE_ENABLE_MOCK_DATA}
        VITE_WS_RECONNECT_INTERVAL: ${VITE_WS_RECONNECT_INTERVAL}
    container_name: heart4edu-frontend-build
    command: "true"
    volumes:
      - web:/app/dist

  copy-dist:
    image: busybox
    depends_on:
      - frontend-build
    volumes:
      - web:/from
      - nginx_html:/to
    command: sh -c "cp -r /from/* /to/"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: heart4edu-nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - copy-dist
    volumes:
      - nginx_html:/usr/share/nginx/html

volumes:
  web:
  nginx_html:
