services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: heart4edu-backend-dev
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ORT_PROVIDERS=${ORT_PROVIDERS}

  frontend:
    image: node:20-slim
    container_name: heart4edu-frontend-dev
    working_dir: /app
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ENABLE_MOCK_DATA=${VITE_ENABLE_MOCK_DATA}
      - VITE_WS_RECONNECT_INTERVAL=${VITE_WS_RECONNECT_INTERVAL}
    depends_on:
      - backend
